// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAA4v874ORra2KWbo0mn8r3roSgOlXFXw',
    appId: '1:1074377623459:web:18bfd75c6136d87067fc16',
    messagingSenderId: '1074377623459',
    projectId: 'demomessenger-5e5a5',
    authDomain: 'demomessenger-5e5a5.firebaseapp.com',
    databaseURL: 'https://demomessenger-5e5a5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demomessenger-5e5a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9M9qdBv7uriWAPZb7Wtlm1WMeeTEQwW0',
    appId: '1:1074377623459:android:6c862578bab3eb9a67fc16',
    messagingSenderId: '1074377623459',
    projectId: 'demomessenger-5e5a5',
    databaseURL: 'https://demomessenger-5e5a5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demomessenger-5e5a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA-tdba_KzdaDDLh10RX9tDTNBJVV7f6Y',
    appId: '1:1074377623459:ios:9139f4e6412774d967fc16',
    messagingSenderId: '1074377623459',
    projectId: 'demomessenger-5e5a5',
    databaseURL: 'https://demomessenger-5e5a5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demomessenger-5e5a5.firebasestorage.app',
    iosBundleId: 'com.example.demoMessenger',
  );
}
